### ISSUE TITLE
Deserialize object to form

### ISSUE THREAD

**Issue by basharov** [chrisdavies/form-to-obj#1]
Is it possible to make a feature that would do a reverse work - populate a form with the data from an object which was generated by the form-to-obj?

**Comment by chrisdavies** [comment]
Hm. That's a good idea. It shouldn't be too hard. I'll probably make it a separate file so it doesn't bloat apps that don't need it.

I'll gladly take a pull-request, if you've got an implementation. Otherwise, I'll probably make this the next thing I do on the side. :)

**Comment by basharov** [comment]
Yeah, I would make it a separate file too. I can have a look at this when I have more time, will create a pull request if I have anything to share.

**Comment by chrisdavies** [comment]
I started thinking about it, and I'm curious what scenario you have in mind. Generally, dynamic forms are generated (and data-bound) by a template language. But serializing them back out to an object is not (that's the job of form-to-obj).

Let's say you've got a form that has a dynamic list of fields:

``` js
  <input name="user[4].name" value="John">
  <input name="user[4].phone" value="1231231234">
  <input name="user[78].name" value="Sally">
  <input name="user[78].phone" value="7778887777">
  <input name="user[10].name" value="Jane">
  <input name="user[10].phone" value="1001001000">
```

The code that generated these without values could easily be made to generate them _with_ values, as it would probably need to be looping over the user array in order to produce its markup, so it would have the appropriate data values readily available to it. 

So I'm not sure what the value of a hypothetical `obj-to-form`utility would be. 

Thoughts?

**Comment by eugene-eeo** [comment]
@chrisdavies currently my use case is for populating the form via data fetched from a remote server (because we don't have the data immediately when the page is loaded). There is no `obj-to-form` utility, so currently what we're doing is just jQuery everywhere, and it's ugly.

**Comment by chrisdavies** [comment]
I think the best solution for `obj-to-form` is just to use client-side templates to generate your forms. E.g. underscore/lodash templates or something similar. That is probably the cleanest/simplest way to ensure your form matches your data. 

Without the use of client-side templates, `obj-to-form` is a more difficult proposition, and essentially would be simply a hacky way to achieve what templating already does.

Dynamic forms is where trickiness comes in, and most interesting web applications have dynamic forms. So, to implement `obj-to-form` properly, it should handle dynamic forms. That means `obj-to-form` would need the ability to generate form elements based on data. And _that_ is exactly what templating is for.

Does that make sense?

**Comment by eugene-eeo** [comment]
:+1: I totally understand + agree. Also I think there will be difficulty in properly filling things like checkboxes or options, and would require (as you said) a very hacky implementation.

**Comment by chrisdavies** [comment]
If you aren't using React or something fancy, and don't feel like slurping in underscore/lodash, this is a really fast, tiny template language:

http://olado.github.io/doT/index.html

I think it weighs in at 1KB or something. I've used it in production a couple of times.
